easy_admin:
    entities:
        #        # List the entity class name you want to manage
        Competition:
            class: App\Entity\AllCompetition
            list:
                actions: [ { name: 'Show' } ]
            show:
                fields:
                    - id
                    - title
                    - content
                    - fee
                    - peoples

        User:
            class: App\Entity\User
            controller: App\Controller\UserAdminController
            list:
                fields:
                    - firstName
                    - lastName
                    - gender
                    - dateOfBirth
                    - city
                    - email
                actions: [ { name: 'Show' } ]
            show:
                fields:
                    - email
                    - firstName
                    - lastName
                    - gender
                    - dateOfBirth
                    - city
                    - country
                    - nationality
                    - participation
